// Objective-C API for talking to github.com/sagernet/sing-box Go package.
//   gobind -lang=objc github.com/sagernet/sing-box
//
// File is generated by gobind. Do not edit.

#ifndef __Box_H__
#define __Box_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class BoxBox;
@class BoxOptions;

@interface BoxBox : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
// skipped method Box.Inbound with unsupported parameter or return types

// skipped method Box.Network with unsupported parameter or return types

// skipped method Box.Outbound with unsupported parameter or return types

- (BOOL)preStart:(NSError* _Nullable* _Nullable)error;
// skipped method Box.Router with unsupported parameter or return types

- (BOOL)start:(NSError* _Nullable* _Nullable)error;
@end

@interface BoxOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Options.Options with unsupported type: github.com/sagernet/sing-box/option.Options

// skipped field Options.Context with unsupported type: context.Context

// skipped field Options.PlatformLogWriter with unsupported type: github.com/sagernet/sing-box/log.PlatformWriter

// skipped method Options.UnmarshalJSONContext with unsupported parameter or return types

@end

// skipped function Context with unsupported parameter or return types


// skipped function New with unsupported parameter or return types


#endif
