
// Objective-C API for talking to the following Go packages
//
//	github.com/sagernet/sing-box
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libbox_FRAMEWORK_H__
#define __Libbox_FRAMEWORK_H__

#include "Box.objc.h"
#include "Universe.objc.h"

#endif
